### ISSUE TITLE
Change docker repository from dockerhub to github packages

### ISSUE THREAD

**Issue by blijblijblij** [blijblijblij/faas-function-node-checker#1]
https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-docker-for-use-with-github-packages

**Comment by blijblijblij** [comment]
Push to multi-registries

The following workflow will connect you to DockerHub and GitHub Container Registry and push the image to these registries.
[
Show workflow](https://github.com/docker/build-push-action)

```
name: ci

on:
  push:
    branches: master

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0

```
